import { CircleFloat } from "@/components/atom/float/circle"

export const CirclesFloat = () => {
    return <>
        <CircleFloat
            color="[--circle-color:var(--secondary-color)]"
            size="[--circle-size:1200px]"
            position="top-[calc(150px+var(--circle-size)/2*-1)]
             left-[calc(50vw-calc(var(--circle-size)/2))]"
        />
        <CircleFloat
            color="[--circle-color:var(--secondary-color)]"
            size="[--circle-size:1200px]"
            position="top-[calc(0px+var(--circle-size)/2*-1)]
             left-[calc(60vw-calc(var(--circle-size)/2))]"
        />
        <CircleFloat
            color="[--circle-color:var(--secondary-color)]"
            size="[--circle-size:1200px]"
            position="top-[calc(0px+var(--circle-size)/2*-1)]
             left-[calc(15vw-calc(var(--circle-size)/2))]"
        />
        <CircleFloat
            color="[--circle-color:_211,_78,_109]"
            size="[--circle-size:1000px]"
            position="top-[calc(150px+var(--circle-size)/2*-1)]
             left-[calc(50vw-calc(var(--circle-size)/2))]"
        />
        <CircleFloat
            color="[--circle-color:_211,_78,_109]"
            size="[--circle-size:1000px]"
            position="top-[calc(200px+var(--circle-size)/2*-1)]
             left-[calc(40vw-calc(var(--circle-size)/2))]"
        />
        <CircleFloat
            color="[--circle-color:_211,_78,_109]"
            size="[--circle-size:1000px]"
            position="top-[calc(250px+var(--circle-size)/2*-1)]
             left-[calc(30vw-calc(var(--circle-size)/2))]"
        />
        <CircleFloat
            color="[--circle-color:_211,_78,_109]"
            size="[--circle-size:1000px]"
            position="top-[calc(300px+var(--circle-size)/2*-1)]
             left-[calc(20vw-calc(var(--circle-size)/2))]"
        />
        <CircleFloat
            color="[--circle-color:_211,_78,_109]"
            size="[--circle-size:2000px]"
            position="bottom-[calc(var(--circle-size)/2*-1)]
             left-[calc(100vw-calc(var(--circle-size)/2))]"
        />
    </>
}